dual_motor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: dual_motor
    joint_speed: 1.17
    motor_master:
        id: 1
        init: 600
        min: 0
        max: 1023
    motor_slave:
        id: 2
